os:
  - linux
language: csharp
mono: 5.2.0
solution: OpenIIoT.Core.sln
install:
  - nuget restore OpenIIoT.Core.sln
script:
  - xbuild /p:Configuration=Release OpenIIoT.Core.sln
  - mono ./packages/xunit.runner.console.2.2.0/tools/xunit.console.exe ./OpenIIoT.Core.Tests/bin/Release/OpenIIoT.Core.Tests.dll
  - mono ./packages/xunit.runner.console.2.2.0/tools/xunit.console.exe ./OpenIIoT.SDK.Tests/bin/Release/OpenIIoT.SDK.Tests.dll
