//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenIIoT.SDK.Packaging.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OpenIIoT.SDK.Packaging.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -----BEGIN PGP PUBLIC KEY BLOCK-----
        ///Version: Keybase OpenPGP v2.0.64
        ///Comment: https://keybase.io/crypto
        ///
        ///xsFNBFjEkToBEACcLJKyznyRxorenPRskRu+JFhbadQXRj0FxNHfG2dkQChUbkvh
        ///c6jF4Iycj7UuMshwQhRz/Se5+1vI20wfv1yGeqdNl1/Mg1LleHqxV01PBqCzWEjP
        ///YNwmN759dL+kX24+iXgGLHg98hdcKVJKbF7tX0zfKNR1WjWsYqlcxO68qWDjHxvh
        ///xG7ne5ddngLp9KPzNsCMiq5GCeCZ84Rn+L1lI07o3FxIl3PtDmm5mvDmE467UdOS
        ///gyjnZHMDyGLqn+3xcwXnC9BxVkYJPH2+CVjbVRNzPzO3mg+3U6dX/YyLxIo7TJdO
        ///9CqOlHI91GeKIBQyTVTU+OJ39MQd+d65av2pXzSZBteiXCJXxTSDj4l/Dp16w+jZ
        ///hFoHoF [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PGPPublicKey {
            get {
                return ResourceManager.GetString("PGPPublicKey", resourceCulture);
            }
        }
    }
}
